# This file defines configuration for the cargo deny command
# Ref: https://github.com/EmbarkStudios/cargo-deny
[graph]
targets = []

[advisories]
ignore = [
    "RUSTSEC-2024-0370", # used in aws-smithy-runtime"
]

[bans]
deny = []
skip = [
    { name = "http", version = "=0.2.12" }, # old dependency from aws-config
    { name = "http-body", version = "=1.0.1" }, # old dependency from aws-runtime, aw-smithy, hyper
    { name = "regex-automata", version = "=0.1.10" }, # old dependency from tracing-subscriber
    { name = "regex-syntax", version = "<=0.7.5" }, # old transitive dependency from cedar_policy_core
    { name = "syn", version = "=1.0.109" }, # old dependency from derive_builder
    { name = "windows-sys", version = "=0.59.0" }, # old dependency from home, mio, ring, socket2, term, tokio
    { name = "aws-smithy-json", version = "=0.60.7" }, # needed by aws-sdk-verified-permissions
    { name = "thiserror", version = "=1.0.69" }, # needed by cedar and aws-smithy-runtime, and the current version of the cla in crates.io
    { name = "thiserror-impl", version = "=1.0.69" },
]
skip-tree = []

[sources]
allow-git = [
    "https://github.com/cedar-policy/cedar-local-agent.git",
]
unknown-registry = "deny"
unknown-git = "deny"

[licenses]
confidence-threshold = 0.93
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC", # simplified MIT
    "MIT",
    "OpenSSL",
    "Unicode-3.0",
]
clarify = [
    # dependency from aws-config, ring has a non-standard license based on OpenSSL
    { name = "ring", expression = "OpenSSL", license-files = [ { path = "LICENSE", hash = 0xbd0eed23 } ] },
]
exceptions = [
]
