name: Build and Test
on:
    workflow_call: # when invoked by any workflow
    workflow_dispatch: # can be invoked manually

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - name: Checkout avp-local-agent
        uses: actions/checkout@v4
      - name: Checkout cedar-local-agent (temporary step)
        uses: actions/checkout@v4
        with:
          repository: cedar-policy/cedar-local-agent
          token: ${{ secrets.CEDAR_LOCAL_AGENT_PAT }}
          path: cedar-local-agent
      - name: Move cedar-local-agent to parent folder
        run: |
          mv ./cedar-local-agent ..
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo fmt --all --check
      - run: RUSTFLAGS="-D warnings -F unsafe-code" cargo build --verbose
      - run: cargo doc --all-features --no-deps
      - run: cargo clippy --all-features
      - run: cargo test --verbose
      - run: cargo test --verbose --no-default-features
      - run: cargo bench --no-run
      - run: cargo audit --deny warnings
#      - uses: EmbarkStudios/cargo-deny-action@v1 # cargo deny check
